name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Docker Build & Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker container to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            docker stop full-cicd || true
            docker rm full-cicd || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/full-cicd-app:latest
            docker run -d \
              --name full-cicd \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/full-cicd-app:latest
